---
language: ruby
cache: bundler
rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0
before_install: gem install bundler -v 2.2.3
script: bundle exec rake
os: osx
osx_image: xcode12.2
jobs:
  allow_failures:
    - os: osx
