#!/usr/bin/env ruby
# frozen_string_literal: true

require 'safari_bookmarks_parser'

begin
  runner = SafariBookmarksParser::Runner.new(ARGV)
  runner.run
rescue SafariBookmarksParser::Error => e
  warn e.message
  exit 1
end
